/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicahiccpmp.universidad;
import com.unicahiccpmp.dao.*;
import java.awt.Color;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author JULIO
 */
public class RectoresFrom extends javax.swing.JDialog {
    
    private Rectores currentRectores;
    private boolean _reloadParent = false;
    private String _mode;
    
    public boolean getReloadParent(){
        return _reloadParent;
    }
    /**
     * Creates new form AlumnoForm
     */
    public RectoresFrom(String Mode, double id) {
        initComponents();
        setModal(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

        _mode = Mode;
        if (!Mode.equals("INS")){
   
            System.out.println(id);
            currentRectores = UniversidadMode.getRectoresById(id);
            jTSiglas.setText(currentRectores.getSIGLAS());
            jTNombreCampus.setText(currentRectores.getNOMBRECAMPUS());
            jTNombreRector.setText(currentRectores.getNOMBREUNIVERSIDAD());   
        } else {
            currentRectores = new Rectores();
        }
        switch(Mode){
            case "INS":
                jLTitle.setText("Agregando nuevo Alumno");
                jBAgregar.setText("Agregar");
                break;
            case "UPD":
                jLTitle.setText(String.format("Actualizando Rectores %.0f %s", currentRectores.getID(), currentRectores.getNOMBRECAMPUS()));
                jBAgregar.setText("Editar");
                break;
            case "DEL":
                jLTitle.setText(String.format("Eliminar Rectores %.0f %s", currentRectores.getID(), currentRectores.getNOMBRECAMPUS()));
                deshabilitarCampos();
                jBAgregar.setText("Eliminar");
                break;
            case "DSP":
                jBAgregar.setVisible(false);
                jBCancelar.setText("Salir");
                deshabilitarCampos();
                jLTitle.setText(String.format("Rectores %.0f %s", currentRectores.getID(), currentRectores.getNOMBRECAMPUS()));
                break;
        }
        
    }
    
    private void deshabilitarCampos(){
         jTSiglas.setEditable(false);
         jTNombreCampus.setEditable(false);
         jTNombreRector.setEditable(false);
    }

    /**
     * Creates new form RectoresFrom
     */
    public RectoresFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jLSiglas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLNombreRector = new javax.swing.JLabel();
        jTSiglas = new javax.swing.JTextField();
        jTNombreCampus = new javax.swing.JTextField();
        jTNombreRector = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLTitle.setText("Ingresando Datos");

        jLSiglas.setText("Siglas Del Campus");

        jLabel1.setText("Nombres Del Campus");

        jLNombreRector.setText("Nombre Del Rector");

        jBAgregar.setText("Agregar");
        jBAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAgregarMouseClicked(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombreRector)
                            .addComponent(jLNombreRector)
                            .addComponent(jLTitle)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLSiglas)
                                    .addComponent(jTSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNombreCampus)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 106, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLTitle)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSiglas)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNombreCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLNombreRector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNombreRector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar)
                    .addComponent(jBCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseClicked
        // TODO add your handling code here:
        boolean _reloadParent = false;
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jBCancelarMouseClicked

    private void jBAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgregarMouseClicked
        // TODO add your handling code here:
        
                //Extrer la informacion
        currentRectores.setSIGLAS(jTSiglas.getText());
        currentRectores.setNOMBREUNIVERSIDAD(jTNombreCampus.getText());
        currentRectores.setNOMBRECAMPUS(jTNombreRector.getText());
        
        //Validaciones Expresiones Regulares
        boolean hayError = false;
        boolean errorNombres = Validaciones.esCadenaVacia(currentRectores.getNOMBRECAMPUS());
        if(errorNombres){
            jTNombreCampus.setBackground(Color.red);
        }else{
            jTNombreRector.setBackground(Color.white);
        }
        System.out.println(errorNombres);
        
        hayError = errorNombres && true;
        //system.out.println(Validador.esCadenaVacia(currentAlumno.getNOMBRES()));
        if(!hayError){
        switch(_mode){
            case "INS":
                _reloadParent = UniversidadMode.agregarRectores(currentRectores);
                break;
            case "UPD":
                _reloadParent = UniversidadMode.editarRectores(currentRectores);
                break;
            case "DEL":
                _reloadParent = UniversidadMode.eliminarRectores(currentRectores);
                break;
        }
        
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }else{
           // JOptionPane.showConfirmDialog(rootPane, jCEstado)
        }                                      
    }//GEN-LAST:event_jBAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RectoresFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RectoresFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RectoresFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RectoresFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RectoresFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLNombreRector;
    private javax.swing.JLabel jLSiglas;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTNombreCampus;
    private javax.swing.JTextField jTNombreRector;
    private javax.swing.JTextField jTSiglas;
    // End of variables declaration//GEN-END:variables
}
